@startuml
left to right direction
skinparam packageStyle rectangle

together {
  actor "Guest" as guest
  actor "Mechanical Engineer" as eng
}
actor "Supabase System" as supa << System >>

package "MechDrive Studio" {
  usecase "Manage Account & Workspace" as UC1
  usecase "Design Mechanical Drives" as UC2
  usecase "Optimize via Q-Learning" as UC3
}

UC1 -[hidden]down-> UC2
UC2 -[hidden]down-> UC3

guest <|- eng : <<inherits>>

guest --> UC1
eng --> UC2
eng --> UC3

UC1 <-- supa
UC2 <-- supa
UC3 <-- supa

@enduml
